### ISSUE TITLE
AttributeError: 'Conv2d' object has no attribute 'weight'

### ISSUE THREAD

**Issue by angrybird-Z** [tanyinghui/Pytorch-DCGAN-with-SN#1]
博主您好，看您名字是中文我就直接打中文了 我看了您文中提到的关于SN的原代码 也对照自己的代码比对您的代码 但是在我将SN加到自己的判别器D网络后，始终会报错AttributeError: 'Conv2d' object has no attribute 'weight' 我想知道您在调试过程中遇到过这个问题吗 以及如何解决的？

**Comment by angrybird-Z** [comment]
期待您的回复

**Comment by lunayht** [comment]
你好，请问这个问题是在哪里出现的呢？

**Comment by angrybird-Z** [comment]
就是我在生成器上也加入SN的话会报错   我看您代码里并没有在生成器中加入只是在判别器中使用SN层  我自己尝试加入的话会报错 您试过吗

**Comment by usrlijing-hahah** [comment]
> 



> 博主您好，看您名字是中文我就直接打中文了 我看了您文中提到的关于SN的原代码 也对照自己的代码比对您的代码 但是在我将SN加到自己的判别器D网络后，始终会报错AttributeError: 'Conv2d' object has no attribute 'weight' 我想知道您在调试过程中遇到过这个问题吗 以及如何解决的？

您好，我也在训练dcgan过程中出现了问题，请问您怎么解决权重问题的呢？我的权重那块总报错，
![image](https://user-images.githubusercontent.com/116712480/226910996-f0510395-4274-4f4e-bd8c-a4d4bff34da2.png)
感谢您的解答

**Comment by lunayht** [comment]
@usrlijing-hahah please check #2
