### ISSUE TITLE
关于dcgan融合sn的问题

### ISSUE THREAD

**Issue by usrlijing-hahah** [tanyinghui/Pytorch-DCGAN-with-SN#2]
博主，我在使用dcgan训练自己的数据集时，在权重那块总是报错，UnpicklingError: invalid load key, '\x96'.
![image](https://user-images.githubusercontent.com/116712480/226904877-afda9d43-f331-4571-a64e-7d84156c0a0a.png)
想问博主提供训练好的权重吗？我在专辑里面找不到有关权重的文件夹
谢谢博主的回答

**Comment by lunayht** [comment]
你好，我之前的`netD_epoch_20.pth`是从2.1 Train from start开始训练的。2.0 Train from checkpoint 是自选的，如没有，可直接从 
```
netG.train()
netD.train()
```
开始训练。

**Comment by usrlijing-hahah** [comment]
> 你好，我之前的`netD_epoch_20.pth`是从2.1 Train from start开始训练的。2.0 Train from checkpoint 是自选的，如没有，可直接从
> 
> ```
> netG.train()
> netD.train()
> ```
> 
> 开始训练。
感谢博主的回答
